### ISSUE TITLE
Images are used instead of code blocks in Android Studio

### ISSUE THREAD

**Issue by NoahBres** [Coppersource/gm0#121]
**What information should be added?**
~~wait why isn't that a code block~~
-dan

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
https://gm0.org/en/stable/docs/software/using-android-studio.html

**Comment by JIceberg** [comment]
I'm so confused

**Comment by dansman805** [comment]
Closed by https://github.com/Coppersource/gm0/pull/122
