### ISSUE TITLE
Proposed resource on software...

### ISSUE THREAD

**Issue by alan412** [Coppersource/gm0#18]
GM0 is an AWESOME resource and thank you for sharing it with the community.

I have recently put out a book about learning Java for FTC (I wrote it in order to help my team members and am hoping it is helpful to others as well.)

Would you consider putting a link to it in your software resources?

You can download the PDF of the book for FREE at:
https://github.com/alan412/LearnJavaForFTC

**Comment by dansman805** [comment]
This has been done; see https://github.com/Coppersource/gm0/commit/ffa3e5b2e6420cd0c83ff0f0f3b8fd3a0301f348#diff-cc0af686d112dcc4d1a4c0199942b028.
