### ISSUE TITLE
Add Information regarding the use of ADB

### ISSUE THREAD

**Issue by dansman805** [Coppersource/gm0#48]
**What information should be added?**
Information about how to use `adb,` where it's located, how to add it to path, wireless adb, etc.

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
As its own section under https://gm0.org/en/stable/docs/software/using-the-sdk.html.

**Comment by NoahBres** [comment]
Ignore the goto point reference. I made an oopsie

**Comment by NoahBres** [comment]
Include STUFF you can do like scrpy for viewing the screen wirelessly or viewing wireless logcat in android studio

**Comment by dansman805** [comment]
The info covered here is now covered under issue https://github.com/Coppersource/gm0/issues/59, so I'm closing this one.
