### ISSUE TITLE
Mecanum Page Doesn't Mention Motor Reversing

### ISSUE THREAD

**Issue by JIceberg** [Coppersource/gm0#68]
**What information should be added?**
The mecanum page should explicitly talk about reversing the direction of the motors as needed.

**Does it need it's own page? (Yes/No):** No

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Programming Tutorial - Mecanum Drive

**Comment by NoahBres** [comment]
Give default motor reverse-ings (right side iirc?) Mention that most of the motors are ccw except for neverest. In which case you're reversing left side.
