### ISSUE TITLE
Game Manual 0, Game Manual 0 in PDF Header

### ISSUE THREAD

**Issue by dansman805** [Coppersource/gm0#73]
**What's broken?**
In the PDF Header, stable or latest, the top left contains "Game Manual 0, Game Manual 0". This should only say "Game Manual 0" once.

**Recreation steps:**

1. Open either latest or stable pdf, go to a random page, look at the top left corner.

**Screenshots**
![Example](https://media.discordapp.net/attachments/225451520911605765/772321867209375744/unknown.png)

**Comment by JIceberg** [comment]
kinda wack

**Comment by dansman805** [comment]
I don't really know how to fix this, it doesn't really matter so I'm closing this.

**Comment by JIceberg** [comment]
rip
