### ISSUE TITLE
Add vision page

### ISSUE THREAD

**Issue by dansman805** [Coppersource/gm0#89]
**What information should be added?**
Talk about Vuforia, Tensorflow, (Easy)OpenCV; mention scrcpy as an option to look at camera output.

**Does it need it's own page? (Yes/No):** Yes

**If it needs a page, which section should it be in? If it doesn't, which page should it be under?**
Make an advanced section under software, then put it under that.

**Comment by shaunsingh** [comment]
Ill try working on this tomorrow (shaurya)

**Comment by shaunsingh** [comment]
https://docs.google.com/document/d/1w6yG1Ph9jYKsGFOdHocUbrGFC1ooq7zbf-JrEdTkf6M/edit?usp=sharing

draft

**Comment by dansman805** [comment]
> Note: Tensorflow cannot run on the older ZTE speed phones, and need a phone with android 6.0 (marshmallow) or higher

All legal android phones can run Tensorflow, and the minimum version for every legal phone is at least marshmallow so this note is redundant.

**Comment by shaunsingh** [comment]
I modified it to remove the redundant lines. I also gave you edit permissions if you think anything else needs editing.

**Comment by NoahBres** [comment]
Basic EOCV pipeline sample? Basic pixel sampling perhaps?

**Comment by shaunsingh** [comment]
eocv section updated with link to examples

**Comment by shaunsingh** [comment]
https://github.com/shaunsingh/gm0/blob/master/source/docs/software/vision.rst

Added file is here. Could someone please test before I PR as I am having issues with my make install

**Comment by shaunsingh** [comment]
https://github.com/Coppersource/gm0/pull/145

**Comment by dansman805** [comment]
Closed by https://github.com/Coppersource/gm0/pull/145

**Comment by dansman805** [comment]
Closed by https://github.com/Coppersource/gm0/pull/145
